Add controllers
DmitriiDerendyaev/Share-it pull request #1
Opened 2023-12-21 19:07 UTC by DmitriiDerendyaev

добавлен каркас приложения ShareIt

2023-12-22 06:35 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +}
Для всех оставшихся исключений обработчик добавить
```
	@ExceptionHandler
	@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
	public ErrorResponse handleThrowable(final Throwable e) {
		log.info("500 {}", e.getMessage(), e);
		return new ErrorResponse(e.getMessage());
	}
```

2023-12-22 06:43 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private final ItemMapper itemMapper;
Для информации. Есть два мнения где размещать маппинг dto в модель и обратно.
1 это в классах сервисов (удобно когда есть другие механизмы взаимодействия с внешним миром кроме rest и маппинг делаем централизованно в одном месте)
2 не в классах сервисов (когда считаем что в сервисах только бизнес логика, сл-но dto как внешней зависимости там не место)
оба мнения имеют право на существование, выбор за разработчиком

2023-12-22 06:47 UTC, VadimZharkov requested changes
Можно улучшить

2023-12-24 09:04 UTC, DmitriiDerendyaev commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +}
Добавил так же обработку исключений при ошибке валидации

2023-12-24 09:05 UTC, DmitriiDerendyaev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private final ItemMapper itemMapper;
Переместил логику в  сервисы

2023-12-25 06:30 UTC, VadimZharkov approved these changes

2024-01-11 18:56 UTC, merged