Add item requests
DmitriiDerendyaev/Share-it pull request #3
Opened 2024-02-03 17:29 UTC by DmitriiDerendyaev

2024-02-05 06:33 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private final String userIDHead = "X-Sharer-User-Id";
Зря поменял определение константы) Было правильней

2024-02-05 06:42 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
```
switch (state) {
            case "ALL":
```
лучше сделать перечислимое, чем сравнивать строки

2024-02-05 06:49 UTC, VadimZharkov requested changes
Можно улучшить

2024-02-05 19:48 UTC, DmitriiDerendyaev commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private final String userIDHead = "X-Sharer-User-Id";
Удивительно, но линтер и наш всеми обожаемый AutoCheckCodeStyleChecker не пропустил в этот раз, сославшись на паттерн:
```
[INFO] There are 3 errors reported by Checkstyle 10.12.6 with checkstyle.xml ruleset.
Error:  src/main/java/ru/practicum/shareit/item/ItemController.java:[23,26] (naming) MemberName: Member name 'USER_ID_HEADER' must match pattern '^[a-z][a-zA-Z0-9]*$'.
Error:  src/main/java/ru/practicum/shareit/booking/BookingController.java:[24,26] (naming) MemberName: Member name 'USER_ID_HEADER' must match pattern '^[a-z][a-zA-Z0-9]*$'.
Error:  src/main/java/ru/practicum/shareit/request/ItemRequestController.java:[26,26] (naming) MemberName: Member name 'USER_ID_HEADER' must match pattern '^[a-z][a-zA-Z0-9]*$'.
```

2024-02-06 09:17 UTC, VadimZharkov approved these changes

2024-02-18 18:30 UTC, merged